#coding utf-8
nomedocurso = input("Qual o curso que estou calculando?")
linguagens = float(input("Peso de linguagens?"))
humanas = float(input("Qual o peso de humanas?"))
natureza = float(input("Qual o peso de naturezas?"))
matematica = float(input("qual o peso de matematica?"))
redacao = float(input("Qual o peso de redação?"))
print("vamos as notas agora")
Li = float(input("linguagens foi quanto?"))
Hu = float(input("humanas foi quanto?"))
Na = float(input("naturezas foi quanto?"))
Ma = float(input("matematica foi quanto?"))
Re = float(input("tirou quanto em reda?"))
print("calculando")
nota_de_corte_sem_dividir = ((linguagens* Li )+(humanas* Hu)+(natureza* Na)+(matematica* Ma)+(Re*redacao))
NCorte = nota_de_corte_sem_dividir/(linguagens+humanas+redacao+matematica+natureza)
print(f"Sua nota de corte para o curso de \n{nomedocurso} foi de {NCorte}")